name: beca_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 0.6.4
  flutter_bloc: ^5.0.0
  meta: ^1.1.6
  equatable: ^1.2.0

dev_dependencies:
  build_runner:
  auto_route_generator: 0.6.4

flutter:
  uses-material-design: true
