name: beca_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: 0.6.4
  flutter_bloc: ^6.0.0
  meta: ^1.1.6
  equatable: ^1.2.0
  chopper: ^2.0.0
  built_value: ^7.1.0
  shared_preferences: ^0.5.8
  url_launcher: ^5.5.0
  share: ^0.6.4+3
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  android: true

dev_dependencies:
  build_runner:
  auto_route_generator: 0.6.4
  chopper_generator: ^2.0.0
  built_value_generator: ^7.1.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/avatars/